/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedIndexRouteImport } from './routes/(protected)/index'
import { Route as protectedYouRouteImport } from './routes/(protected)/you'
import { Route as protectedWatchRouteImport } from './routes/(protected)/watch'
import { Route as protectedTweetsRouteImport } from './routes/(protected)/tweets'
import { Route as protectedSubscriptionsRouteImport } from './routes/(protected)/subscriptions'
import { Route as protectedUserIdRouteImport } from './routes/(protected)/$userId'
import { Route as authSignupRouteImport } from './routes/(auth)/Signup'
import { Route as authLoginRouteImport } from './routes/(auth)/Login'
import { Route as protectedPlaylistPlaylistIdRouteImport } from './routes/(protected)/playlist.$playlistId'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedYouRoute = protectedYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedWatchRoute = protectedWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedTweetsRoute = protectedTweetsRouteImport.update({
  id: '/tweets',
  path: '/tweets',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSubscriptionsRoute = protectedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUserIdRoute = protectedUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/Signup',
  path: '/Signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedPlaylistPlaylistIdRoute =
  protectedPlaylistPlaylistIdRouteImport.update({
    id: '/playlist/$playlistId',
    path: '/playlist/$playlistId',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/Login': typeof authLoginRoute
  '/Signup': typeof authSignupRoute
  '/$userId': typeof protectedUserIdRoute
  '/subscriptions': typeof protectedSubscriptionsRoute
  '/tweets': typeof protectedTweetsRoute
  '/watch': typeof protectedWatchRoute
  '/you': typeof protectedYouRoute
  '/': typeof protectedIndexRoute
  '/playlist/$playlistId': typeof protectedPlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/Login': typeof authLoginRoute
  '/Signup': typeof authSignupRoute
  '/$userId': typeof protectedUserIdRoute
  '/subscriptions': typeof protectedSubscriptionsRoute
  '/tweets': typeof protectedTweetsRoute
  '/watch': typeof protectedWatchRoute
  '/you': typeof protectedYouRoute
  '/': typeof protectedIndexRoute
  '/playlist/$playlistId': typeof protectedPlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/Login': typeof authLoginRoute
  '/(auth)/Signup': typeof authSignupRoute
  '/(protected)/$userId': typeof protectedUserIdRoute
  '/(protected)/subscriptions': typeof protectedSubscriptionsRoute
  '/(protected)/tweets': typeof protectedTweetsRoute
  '/(protected)/watch': typeof protectedWatchRoute
  '/(protected)/you': typeof protectedYouRoute
  '/(protected)/': typeof protectedIndexRoute
  '/(protected)/playlist/$playlistId': typeof protectedPlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/Login'
    | '/Signup'
    | '/$userId'
    | '/subscriptions'
    | '/tweets'
    | '/watch'
    | '/you'
    | '/'
    | '/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/Login'
    | '/Signup'
    | '/$userId'
    | '/subscriptions'
    | '/tweets'
    | '/watch'
    | '/you'
    | '/'
    | '/playlist/$playlistId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(protected)'
    | '/(auth)/Login'
    | '/(auth)/Signup'
    | '/(protected)/$userId'
    | '/(protected)/subscriptions'
    | '/(protected)/tweets'
    | '/(protected)/watch'
    | '/(protected)/you'
    | '/(protected)/'
    | '/(protected)/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/you': {
      id: '/(protected)/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof protectedYouRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/watch': {
      id: '/(protected)/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof protectedWatchRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/tweets': {
      id: '/(protected)/tweets'
      path: '/tweets'
      fullPath: '/tweets'
      preLoaderRoute: typeof protectedTweetsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/subscriptions': {
      id: '/(protected)/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof protectedSubscriptionsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/$userId': {
      id: '/(protected)/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof protectedUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/Signup': {
      id: '/(auth)/Signup'
      path: '/Signup'
      fullPath: '/Signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/Login': {
      id: '/(auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/playlist/$playlistId': {
      id: '/(protected)/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof protectedPlaylistPlaylistIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedUserIdRoute: typeof protectedUserIdRoute
  protectedSubscriptionsRoute: typeof protectedSubscriptionsRoute
  protectedTweetsRoute: typeof protectedTweetsRoute
  protectedWatchRoute: typeof protectedWatchRoute
  protectedYouRoute: typeof protectedYouRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedPlaylistPlaylistIdRoute: typeof protectedPlaylistPlaylistIdRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedUserIdRoute: protectedUserIdRoute,
  protectedSubscriptionsRoute: protectedSubscriptionsRoute,
  protectedTweetsRoute: protectedTweetsRoute,
  protectedWatchRoute: protectedWatchRoute,
  protectedYouRoute: protectedYouRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedPlaylistPlaylistIdRoute: protectedPlaylistPlaylistIdRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
